Fat 9816/1
arhipy97/online-newspaper_js pull request #1
Opened 2020-10-20 15:08 UTC by arhipy97

1. Ушёл от изначальной концепции Store, буду думать как его передавать сразу в компонент(если ты имел в виду extend от него все остальные классы- завтра исправлю ), в данном случае передавал через переменную photosArray.

2020-10-21 06:20 UTC, EugeneSolovyev requested changes

2020-10-21 06:20 UTC, EugeneSolovyev commented on src/components/store/index.js
> +        await res.json()
```js
const json = await res.json()
```
если уже работаешь с async/await то работай с ним

2020-10-21 06:20 UTC, EugeneSolovyev commented on src/components/store/index.js
> +        await res.json()
так же смотри, запрос к бэку логически надо выносить в отдельный класс. EventIniter как бы у тебя не требует расширения и более того, добавление новых методов нарушает SOLID принципы.
Возвращаясь к вопросу: тебе нужен вспомогательный класс для работы с нетворком.
```js
export default class API {
  constructor(instance) {
    this.api = instance;
  }

  getResource(path) {
    this.api.getResource(path)
  }

  postResource(path, body) {
    this.api.postResource(path, body)
  }

  putResource(path, body) {
    this.api.putResource(path, body)
  }

  deleteResource(path) {
    this.api.deleteResource(path)
  }
}

// в другом файле мы создаем инстанс для работы с апи
const BACKEND_BASE_PATH = 'https://blabla/'
class FetchAPI {
  async getResource(path) {
    const result = await fetch(`${BACKEND_BASE_PATH}${path})
    return await result.json()
  }

  postResource(path, body) {
    const result = await fetch(`${BACKEND_BASE_PATH}${path}, body)
    return await result.json()
  }

  putResource(path, body) {
    const result = await fetch(`${BACKEND_BASE_PATH}${path}, body)
    return await result.json()
  }

  deleteResource(path) {
    const result = await fetch(`${BACKEND_BASE_PATH}${path})
    return await result.json()
  }
}
// и где-то в проекте ты создаешь
const api = new API(new FetchAPI())
api.getResource('/posts')
```
Собственно почему через 2 класса - например я завтра приду к тебе и скажу, что давай делать не через бэк а тупо хранить всё в локал сторадже, вместо того чтобы переделывать всё, ты создаешь новый класс LocalStorageAPI с тем же набором методов и передашь в new API

Ну и логически в EventEmmiter не должно быть обращений к апихе, это прям супер важно

2020-10-21 06:20 UTC, EugeneSolovyev commented on src/index.js
> +    let photosArray
ты можешь тут работать с async/await
но если хочешь с промисами, то не надо создавать лишние вариэйблы
если ты посидишь и подумаешь, то поймешь что 
1)
```
.then(()=> document.getElementById("header").innerHTML = header.render())
.then(()=> document.getElementById("main").innerHTML += main.render())
```
этих пацанов можно проинитить в самом конце или в самом начале
2) 
почему не так?
```
store.getResource("photos")
        .then(() => store.getValue("photos"))
        .then(photosArray => main.renderPhotoArticles(photosArray, 10))
```

2020-10-22 06:57 UTC, EugeneSolovyev requested changes

2020-10-22 06:57 UTC, EugeneSolovyev commented on src/components/API-wrapper/index.js
> +export default class API_WRAPPER{
Классы называются через PascalCase
а ты объявил класс как будто это КОНСТАНТА

2020-10-22 06:57 UTC, EugeneSolovyev commented on src/components/API-wrapper/index.js
> +        throw Error("Need template!")
при чем тут рендер?

2020-10-22 06:57 UTC, EugeneSolovyev commented on src/components/API-wrapper/index.js
> +        return this.api.getStoreValue(field)
при чем тут стор?

2020-10-22 06:57 UTC, EugeneSolovyev commented on src/components/store/index.js
> +        // console.log("++");
закомментированный код и консол логи мы удаляем, они в 146% случаев не пригодятся

2020-10-22 06:57 UTC, EugeneSolovyev commented on src/index.js
> +    // await console.log(api.getStoreValue("photos"));
удаляем закомментированный код

2020-10-26 06:45 UTC, EugeneSolovyev requested changes

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +        })
вместо форыча, можно использовать reduce
```js
return arr.reduce((result, current, index) => {
   if (index > quality) return result;

  return `${result}${this.createSidePhotoItem(current)}`
}, '')

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +class SidePhotoContent{
тут вроде вьюха используется, получается что это компонент
а ты не наследуешься от того класса который мы сделали

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +                        <p class="subtitle">${value['title']}</p>
value.title
почему у тебя так написано?

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +                    <img class="left-side-content__img" src="${value['url']}" alt="picture">
value.url
почему у тебя тут именно так написано?

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/components/utils/ApiFetch/index.js
> +        return obj
а что если arrOfKeys и arrOfValues имеют разную длину?
у тебя часть из arrOfValues просто не будет использоваться
что ты хотел тут сделать и для чего?

2020-10-26 06:45 UTC, EugeneSolovyev commented on src/index.js
> +    })
обсуждали в пятницу по поводу коллбэков
наверное надо вынести в переменную или в функцию

2020-10-26 12:52 UTC, arhipy97 commented on src/components/API_content/sidePhotoLayout/index.js
> +                        <p class="subtitle">${value['title']}</p>
Для отрисовки я передаю данные из store, там есть поле title.

2020-10-26 12:58 UTC, arhipy97 commented on src/components/utils/ApiFetch/index.js
> +        return obj
Получение данных у меня организовано через промис all, и ничего лучшего я не придумал, как создать отдельый метод для их упорядочивания в объект с полями (те же названия, что и переданы для fetch),
который в последствии я просто тусую в Store.

2020-11-02 12:53 UTC, EugeneSolovyev requested changes

2020-11-02 12:53 UTC, EugeneSolovyev commented on debug.log
> +[1016/004839.817:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
.log файлы надо положить в gitignore

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/API_content/commentLayout/index.js
> +    createCommentItem(user) {
деструктурируй в параметрах до name, email и body

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/API_content/commentLayout/index.js
> +        return commentsHTML += `
`+=`
не надо так делать
используй шаблонные строки, либо просто `+` - эфект тот же

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +        }, "")
тут у тебя повторяющаяся логика
можно использовать один класс, вместо двух
если очень надо как-то сепарироваться, то можно объеденить в фабрику (показывал тебе как не так давно)

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/API_content/sidePhotoLayout/index.js
> +                `
повтор

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/utils/ApiFetch/index.js
> +    }
если тебе нужно сделать асинхронный метод в классе, то ты можешь сделать так
```js
async get(path) {
  //...
}
```
не нужно делать стрелочные тут

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/utils/localStorage/index.js
> +        const FIELD = `${this.keyName}${postId}`
postId
у тебя локал сторадж будет только с пост айди работать?

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/components/utils/localStorage/index.js
> +        return commentsLocalStorage !== null ? JSON.parse(commentsLocalStorage): [];
```js
return JSON.parse(localStorage.getItem(`${this.keyName}${postId}`) || '[]')
```
это норм практика

2020-11-02 12:53 UTC, EugeneSolovyev commented on src/index.js
> +    let links = {
используй `const`, врядли ты будешь переопределять

2020-11-02 13:15 UTC, arhipy97 commented on src/components/utils/localStorage/index.js
> +        const FIELD = `${this.keyName}${postId}`
Метод специализирован для комментариев, я их классифицирую по postId.

2020-11-02 13:16 UTC, arhipy97 commented on src/components/API_content/sidePhotoLayout/index.js
> +        }, "")
Методы различаются всё же,
 не вижу разницы, переопределять метод или же просто написать новый класс.
Будет тот же объём кода.

2020-11-03 15:25 UTC, EugeneSolovyev requested changes

2020-11-03 15:25 UTC, EugeneSolovyev commented on src/components/utils/BtnHandler/index.js
> +        elem.onclick = this.onClick.bind(this)
подумай нужно оно тебе?
```js
// <button name="/posts/1">Read more about ${title}</button>
class BtnHandler {
  constructor(elem, onClick) {
    this.elem = elem
    this.onClickCallback = onClick
    this.elem.addEventListenter('click keydown', onClick) // нужно в конструкторе
  }

  destroy() {
     this.elem.removeEventListener('click keydown', onClick) 
  }
}
```

2020-11-03 15:25 UTC, EugeneSolovyev commented on src/components/utils/router/index.js
> +    }
фетчинг данных должен быть не в роутере, а в компоненте
id - передается в класс и в классе компонент на основании айди футчим пост

фетчинг данных поста в роутере или в main файле - плохая практика

2020-11-03 15:25 UTC, EugeneSolovyev commented on src/components/utils/router/index.js
> +        this.links = links;
линкс тебе не нужны (см. коммент ниже)

2020-11-27 12:55 UTC, merged